#pragma once

// Name: AWL, Version: 4.24.3


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.AnimGraph
struct UMixamoBattalionAnimator_C_AnimGraph_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_C5C43C7248B78C3472BF20B936660237
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_C5C43C7248B78C3472BF20B936660237_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_FA69590443C64085029980A306326B58
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_FA69590443C64085029980A306326B58_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_77F1A84D4C829389959FA28FE87425C7
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_77F1A84D4C829389959FA28FE87425C7_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_E0266567476ACF3B5CE7F3AAF162B7FD
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_E0266567476ACF3B5CE7F3AAF162B7FD_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_444EDB2F4C4B64FF24F6DDA4B5777476
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_444EDB2F4C4B64FF24F6DDA4B5777476_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_DC3FAA554D39D990349C94BD083526E2
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_DC3FAA554D39D990349C94BD083526E2_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_87ACAE244CC1F328EAD4529600FCB74E
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_87ACAE244CC1F328EAD4529600FCB74E_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_2E05D11B44624ADFE4BE06BC24B19D29
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_2E05D11B44624ADFE4BE06BC24B19D29_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_65A20ABF4E119F33A7938DB7DADF81C6
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_65A20ABF4E119F33A7938DB7DADF81C6_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_449E612F41CE177BBB703DA955871CD3
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_449E612F41CE177BBB703DA955871CD3_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_7C54D86B42A2C9499174D78CADFF59D3
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_7C54D86B42A2C9499174D78CADFF59D3_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_026F7C0E447E942FA609F1B934C40BDC
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_026F7C0E447E942FA609F1B934C40BDC_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_5BA9B91B4E33DCEE4109E99AC9D00D0D
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_5BA9B91B4E33DCEE4109E99AC9D00D0D_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_BE3B13D642D3A96BB29EE3A38947889E
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_BE3B13D642D3A96BB29EE3A38947889E_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_2B153A074813E68E8B09CC83CF5FFC84
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_2B153A074813E68E8B09CC83CF5FFC84_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_BB78D9884BE856373E021B8A67E09326
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_BB78D9884BE856373E021B8A67E09326_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.BlueprintUpdateAnimation
struct UMixamoBattalionAnimator_C_BlueprintUpdateAnimation_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.BlueprintInitializeAnimation
struct UMixamoBattalionAnimator_C_BlueprintInitializeAnimation_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.AnimNotify_EnableMovement
struct UMixamoBattalionAnimator_C_AnimNotify_EnableMovement_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.AnimNotify_DisableMovement
struct UMixamoBattalionAnimator_C_AnimNotify_DisableMovement_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.AnimNotify_RFoot
struct UMixamoBattalionAnimator_C_AnimNotify_RFoot_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.AnimNotify_LFoot
struct UMixamoBattalionAnimator_C_AnimNotify_LFoot_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.AnimNotify_HandsEffector
struct UMixamoBattalionAnimator_C_AnimNotify_HandsEffector_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.CheckStepsType
struct UMixamoBattalionAnimator_C_CheckStepsType_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.PlayStep
struct UMixamoBattalionAnimator_C_PlayStep_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_BE3959784DC667FA51D23E9DD25702E3
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_BE3959784DC667FA51D23E9DD25702E3_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.ExecuteUbergraph_MixamoBattalionAnimator
struct UMixamoBattalionAnimator_C_ExecuteUbergraph_MixamoBattalionAnimator_Params
{
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
