#pragma once

// Name: AWL, Version: 4.24.3


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.AnimGraph
struct UMixamoBattalionAnimatorBOT_C_AnimGraph_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_C2C90A854ADAF93A37200F97598544B7
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_C2C90A854ADAF93A37200F97598544B7_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_CA2B10E44914A7879AD9D28E37957F32
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_CA2B10E44914A7879AD9D28E37957F32_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_036E6BCD48AA21DDA54A9A841A65EAE6
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_036E6BCD48AA21DDA54A9A841A65EAE6_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_9C0EAF964166BF29DB66A5AD81EAB77D
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_9C0EAF964166BF29DB66A5AD81EAB77D_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_31756EB44FB160DEE3C08FA3B9B32068
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_31756EB44FB160DEE3C08FA3B9B32068_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_E160B69A492720BCE835F29DF1D5FC02
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_E160B69A492720BCE835F29DF1D5FC02_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_99898AF4435DC12524C676925216311C
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_99898AF4435DC12524C676925216311C_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_254113304A79820A169187AE40F45BF4
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_254113304A79820A169187AE40F45BF4_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_4F4D21CC4569756A5413499567A7E329
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_4F4D21CC4569756A5413499567A7E329_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_1E14DF5B4DD09FD27A72FEB436ED37A7
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_1E14DF5B4DD09FD27A72FEB436ED37A7_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_3D3C04D24519FF8FFBCFDFA443584A96
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_3D3C04D24519FF8FFBCFDFA443584A96_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_25F2D2FD40C631B9D52F1BADDC9254CB
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_25F2D2FD40C631B9D52F1BADDC9254CB_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_1C86288C46282404FA010CB61CC45BD4
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_1C86288C46282404FA010CB61CC45BD4_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_AF3FD3A74D2A7E461E6560A55783F7C3
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_AF3FD3A74D2A7E461E6560A55783F7C3_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_B7102E7E4F9CB699B92CD681835A6CD7
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_B7102E7E4F9CB699B92CD681835A6CD7_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_C48929054551EC3638C336BF308D67D7
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_C48929054551EC3638C336BF308D67D7_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.BlueprintUpdateAnimation
struct UMixamoBattalionAnimatorBOT_C_BlueprintUpdateAnimation_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.AnimNotify_EnableMovement
struct UMixamoBattalionAnimatorBOT_C_AnimNotify_EnableMovement_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.AnimNotify_DisableMovement
struct UMixamoBattalionAnimatorBOT_C_AnimNotify_DisableMovement_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.AnimNotify_RFoot
struct UMixamoBattalionAnimatorBOT_C_AnimNotify_RFoot_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.AnimNotify_LFoot
struct UMixamoBattalionAnimatorBOT_C_AnimNotify_LFoot_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.CheckLodSystem
struct UMixamoBattalionAnimatorBOT_C_CheckLodSystem_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.CheckStepsType
struct UMixamoBattalionAnimatorBOT_C_CheckStepsType_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.PlayStep
struct UMixamoBattalionAnimatorBOT_C_PlayStep_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.BlueprintInitializeAnimation
struct UMixamoBattalionAnimatorBOT_C_BlueprintInitializeAnimation_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.ExecuteUbergraph_MixamoBattalionAnimatorBOT
struct UMixamoBattalionAnimatorBOT_C_ExecuteUbergraph_MixamoBattalionAnimatorBOT_Params
{
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
