#pragma once

// Name: AWL, Version: 4.24.3


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function Z_Animator.Z_Animator_C.AnimGraph
struct UZ_Animator_C_AnimGraph_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_ADB31EC54EBD72969CC2CEA7CDE3F181
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_ADB31EC54EBD72969CC2CEA7CDE3F181_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_6D02BF5A464FAC6EEE21B9915BCDE6A6
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_6D02BF5A464FAC6EEE21B9915BCDE6A6_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_7FA8D0A04A7DA5E4AE279B8280ABBF2C
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_7FA8D0A04A7DA5E4AE279B8280ABBF2C_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_71F774C949E938A1D605FCBFFED99DEF
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_71F774C949E938A1D605FCBFFED99DEF_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_4E6CCDF04B536F472ABF07B1C8938C1F
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_4E6CCDF04B536F472ABF07B1C8938C1F_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_3B73FFDB4DF6B61006558292D7BEE0DD
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_3B73FFDB4DF6B61006558292D7BEE0DD_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_D39F771649AA24DE1A8D85901562585B
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_D39F771649AA24DE1A8D85901562585B_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_2641F3CB4C33DA644CFCABA8EF287359
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_2641F3CB4C33DA644CFCABA8EF287359_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_52CCF1DD42A62E50A6FB01A0EBECC4F3
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_52CCF1DD42A62E50A6FB01A0EBECC4F3_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_463B3FDB41D4FCF9466F4C9982AADE3D
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_463B3FDB41D4FCF9466F4C9982AADE3D_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_D7F694CA476054253EF58EBFC2002723
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_D7F694CA476054253EF58EBFC2002723_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_0A13755C4BFC79071D713B980FC9BEC1
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_0A13755C4BFC79071D713B980FC9BEC1_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_078E15404B41D9FC98A2AE80527A72A8
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_078E15404B41D9FC98A2AE80527A72A8_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_7083F5264E41E6B3841366A6599FE1F2
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_7083F5264E41E6B3841366A6599FE1F2_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_083357084C64F3CE6D394DA2C4D0C191
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_083357084C64F3CE6D394DA2C4D0C191_Params
{
};

// Function Z_Animator.Z_Animator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_16CD2E0644FFE8D6E9A5FAACE7065F92
struct UZ_Animator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Z_Animator_AnimGraphNode_TransitionResult_16CD2E0644FFE8D6E9A5FAACE7065F92_Params
{
};

// Function Z_Animator.Z_Animator_C.BlueprintUpdateAnimation
struct UZ_Animator_C_BlueprintUpdateAnimation_Params
{
};

// Function Z_Animator.Z_Animator_C.AnimNotify_EnableMovement
struct UZ_Animator_C_AnimNotify_EnableMovement_Params
{
};

// Function Z_Animator.Z_Animator_C.AnimNotify_DisableMovement
struct UZ_Animator_C_AnimNotify_DisableMovement_Params
{
};

// Function Z_Animator.Z_Animator_C.AnimNotify_RFoot
struct UZ_Animator_C_AnimNotify_RFoot_Params
{
};

// Function Z_Animator.Z_Animator_C.AnimNotify_LFoot
struct UZ_Animator_C_AnimNotify_LFoot_Params
{
};

// Function Z_Animator.Z_Animator_C.CheckLodSystem
struct UZ_Animator_C_CheckLodSystem_Params
{
};

// Function Z_Animator.Z_Animator_C.CheckStepsType
struct UZ_Animator_C_CheckStepsType_Params
{
};

// Function Z_Animator.Z_Animator_C.PlayStep
struct UZ_Animator_C_PlayStep_Params
{
};

// Function Z_Animator.Z_Animator_C.BlueprintInitializeAnimation
struct UZ_Animator_C_BlueprintInitializeAnimation_Params
{
};

// Function Z_Animator.Z_Animator_C.ExecuteUbergraph_Z_Animator
struct UZ_Animator_C_ExecuteUbergraph_Z_Animator_Params
{
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
